user-examples/example-embedded/pom.xml, user-examples/example-remote/pom.xml, user-examples/pom.xml
The user examples did not build. Set parent pom to de.dfki.mary.
=> Make user examples build

pom.xml
=> add support for groovy compilation

marytts-runtime/src/main/java/marytts/modules/JPhonemiser.java
also improve logging
closes #369
=> handle exceptions on missing or malformed userdict entries

marytts-languages/marytts-lang-en/src/main/java/marytts/language/en/Preprocess.java
Solve parse date locale bug #381
=> Force english locale for parsing date when english language is used

marytts-languages/marytts-lang-it/pom.xml, marytts-languages/marytts-lang-it/src/main/java/marytts/language/it/preprocess/NumberEP.java, marytts-languages/marytts-lang-it/src/test/java/marytts/language/it/PreprocessTest.java
This will solve the issue #432
=> Modified RegEx to accomodate large numbers

marytts-signalproc/src/main/java/marytts/signalproc/adaptation/codebook/WeightedCodebookMfccMapper.java
These subexpressions are identical.
=> Duplicate subexpressions in WeightedCodebookMfccMapper.java

marytts-languages/marytts-lang-en/src/main/java/marytts/language/en/Preprocess.java, marytts-languages/marytts-lang-en/src/test/java/marytts/language/en/PreprocessTest.java
This pull request aims to correct the contraction problem ("that's" is not splitted to "that" and "'s") and double quotes are not considerated as punctuation anymore
=> preprocessing contraction and double quotes correction

marytts-languages/marytts-lang-en/src/test/java/marytts/language/en/OpenNLPPosTaggerIT.java, marytts-languages/marytts-lang-en/src/test/resources/marytts/language/en/exampleshift-en_US.partsofspeech, marytts-languages/marytts-lang-en/src/test/resources/marytts/language/en/exampleshift-en_US.words, marytts-languages/marytts-lang-en/src/test/resources/marytts/language/en/examplesingle-en_US.partsofspeech, marytts-languages/marytts-lang-en/src/test/resources/marytts/language/en/examplesingle-en_US.words, marytts-runtime/src/main/java/marytts/modules/OpenNLPPosTagger.java
=> solving POS shifting problem

marytts-languages/marytts-lang-en/src/main/java/marytts/language/en/Preprocess.java, marytts-runtime/src/main/java/marytts/modules/JPhonemiser.java
=> solving quotes phonetisation problem

marytts-builder/src/main/java/marytts/tools/voiceimport/PhoneLabelFeatureAligner.java
but of course the problems are not solved automatically!
closes #531
=> don't crash in headless environment

marytts-languages/marytts-lang-de/src/main/java/marytts/language/de/preprocess/NetEP.java
shoudl solve #606. for now I haven't design a test as I think this all preprocess for german should be homogenize with english. So for now I just solve this bug and open a more global issue for the homogenization part
=> Solving #606

download/marytts-components.xml
created by Nickolay Shmyrev
closes #603
=> add three Russian unit-selection voices

marytts-common/pom.xml
=> make version property available to test run with maven

buildLogic.gradle
=> configure java source encoding

marytts-languages/marytts-lang-de/src/main/java/marytts/language/de/preprocess/MeasureEP.java
=> Bugfix in german - MeasureEP

marytts-languages/marytts-lang-de/build.gradle, marytts-languages/marytts-lang-de/src/main/resources/marytts/language/de/de.config, marytts-languages/marytts-lang-en/build.gradle, marytts-languages/marytts-lang-en/src/main/resources/marytts/language/en/en.config
Resources are identical to those from http://opennlp.sourceforge.net/models-1.5/, so resolve them as dependencies from there instead.
=> Drop binary maxent models

marytts-builder/src/main/java/marytts/tools/dbselection/DBHandler.java
=> Fix some cases where Data is too long

README.md, applicationLogic.gradle, marytts-runtime/conf/marybase.config, marytts-runtime/src/main/java/marytts/server/Mary.java, marytts-runtime/src/main/java/marytts/server/MaryProperties.java, marytts-runtime/src/main/java/marytts/server/MaryServer.java, marytts-runtime/src/main/java/marytts/server/http/MaryHttpServer.java, marytts-runtime/src/main/resources/marytts/config/marybase.config
Extension of #955 by propagating everything to gradle
=> Make IP address binding configurable

CHANGELOG.md, build.gradle, marytts-common/src/main/java/marytts/util/string/PrintfFormat.java, marytts-runtime/src/main/java/marytts/server/http/MaryHttpServer.java, marytts-runtime/src/main/java/marytts/unitselection/data/HnmTimelineReader.java, marytts-runtime/src/main/resources/marytts/server/http/documentation.html, publishLogic.gradle
=> Publishing

marytts-languages/marytts-lang-en/src/main/java/marytts/language/en/Preprocess.java, marytts-languages/marytts-lang-en/src/test/java/marytts/language/en/PreprocessTest.java
=> English Preprocess
